### ISSUE TITLE
ESIP-4: The Ethscriptions Virtual Machine Discussion

### ISSUE THREAD

**Issue by RogerPodacter** [ethscriptions-protocol/ESIP-Discussion#7]
Read the ESIP here: https://docs.ethscriptions.com/esips/esip-4-the-ethscriptions-virtual-machine

**Comment by BSCNFTs** [comment]
Creating a smart contract sandbox is easy. It can be used to check if a tool is malicious. Below that I added some code for a gas limiter as well for this specific smart contract. 


// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract SmartContractSandbox {
    struct Contract {
        address owner;
        bytes code;
        bool isMalicious;
    }
    
    mapping(uint256 => Contract) public contracts;
    uint256 public contractCount;

    event ContractUploaded(uint256 indexed contractId, address indexed owner);
    event ContractExecuted(uint256 indexed contractId, address indexed executor);

    modifier onlyOwner(uint256 contractId) {
        require(msg.sender == contracts[contractId].owner, "Not contract owner");
        _;
    }

    function uploadContract(bytes memory _code) external {
        uint256 newContractId = contractCount;
        contracts[newContractId] = Contract(msg.sender, _code, false);
        contractCount++;
        emit ContractUploaded(newContractId, msg.sender);
    }

    function executeContract(uint256 contractId) external onlyOwner(contractId) {
        Contract storage contractData = contracts[contractId];
        require(!contractData.isMalicious, "Contract is marked as malicious");
        
        // Execute the contract code in a controlled environment
        // Implement gas limits, whitelisting, and other security measures
        
        // Simulate contract execution (for demonstration purposes)
        // This is a simplified example and should be replaced with an actual execution environment
        contractData.isMalicious = simulateContractExecution(contractData.code);
        
        emit ContractExecuted(contractId, msg.sender);
    }

    function simulateContractExecution(bytes memory _code) internal view returns (bool) {
        // Simulate contract execution and perform dynamic analysis
        // Check for malicious behavior and return true if detected
        
        // In a real implementation, you would use dynamic analysis tools to detect malicious behavior
        // For example, checking for unauthorized access, excessive gas usage, reentrancy, etc.
        
        // For the sake of this example, we'll return false
        return false;
    }
}


Gas limiter code snippet

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract SmartContractSandbox {
    // ... (rest of the contract)

    function executeContract(uint256 contractId) external onlyOwner(contractId) {
        Contract storage contractData = contracts[contractId];
        require(!contractData.isMalicious, "Contract is marked as malicious");
        
        // Implement gas limits to prevent resource-intensive or infinite loops
        uint256 startGas = gasleft();
        require(startGas >= MINIMUM_GAS_REQUIRED, "Insufficient gas for execution");
        
        // Execute the contract code in a controlled environment
        // Implement other security measures
        
        // Simulate contract execution (for demonstration purposes)
        bool isMalicious = simulateContractExecution(contractData.code);
        
        // Calculate gas used and check against gas limit
        uint256 gasUsed = startGas - gasleft();
        require(gasUsed <= MAXIMUM_GAS_ALLOWED, "Exceeded gas limit");

        // Update contract status
        contractData.isMalicious = isMalicious;
        
        emit ContractExecuted(contractId, msg.sender);
    }
    
    // ... (rest of the contract)
}

**Comment by RogerPodacter** [comment]
I like it! But how do we actually implement gas limits in Ruby? Seems tricky!

**Comment by RogerPodacter** [comment]
Maybe we can use https://github.com/tario/shikashi

**Comment by BSCNFTs** [comment]
class SmartContractSandbox
  MINIMUM_GAS_REQUIRED = 100000  # Example minimum required gas
  MAXIMUM_GAS_ALLOWED = 2000000  # Example maximum allowed gas

  def initialize
    @contracts = {}
    @contract_count = 0
  end

  def execute_contract(contract_id)
    contract_data = @contracts[contract_id]
    raise "Not contract owner" unless contract_data[:owner] == msg.sender
    raise "Contract is marked as malicious" if contract_data[:is_malicious]

    start_gas = gasleft()
    raise "Insufficient gas for execution" unless start_gas >= MINIMUM_GAS_REQUIRED

    # Execute the contract code in a controlled environment
    # Implement other security measures

    # Simulate contract execution (for demonstration purposes)
    is_malicious = simulate_contract_execution(contract_data[:code])

    # Calculate gas used and check against gas limit
    gas_used = start_gas - gasleft()
    raise "Exceeded gas limit" unless gas_used <= MAXIMUM_GAS_ALLOWED

    # Update contract status
    contract_data[:is_malicious] = is_malicious

    emit_contract_executed(contract_id, msg.sender)
  end

  # ... (rest of the contract methods)
end

**Comment by KenTheWhaleGoddess** [comment]
As we discussed on discord...

RE " DC-SC bridging"

A downside (also an upside in some sense) of sending the txs to address(0) is you cannot add a receive fallback function to execute some logic. 
Pro would be gas, so sending to zero address should be supported by the protocol...
However you would want a way for a dumb contract execution to impact a smart contract in storage in some cases. 
- What cases? Suppose i (Ethscription Buyer) want to send ETH native token to someone (Ethscription Seller), but only if they have sent the ethscription to me.
- Same with ERC20?

Essentially I am suggesting a way to emit events or store data in a smart contract, in some cases only (where bridging is required and some gas expenditure is acceptable) 

This can be done in the standard fallback function for ETH receipt (can also be done with ERC1155)

First the Buyer would send in msg.data not a DC TX, but the DC TX they would spend ETH to have executed. 

Eg "I am staking .1 ETH, i will release it if Seller performs XYZ send operation" with some withdraw condition as well 

Upon receipt of the Buyer's stake, the msg.data (again not a DC TX but a DC TX they want) is hashed (preprocessed off chain I think is good), and stored in some set or map..

When someone sends the actual DC TX, we verify that this is the hashed event is in the set/mapping, then release the ether..

This would require some Bridge Smart Contract address that is acceptable for ethscriptions (not just address(0)).
```
function receive() external payable {
    if (msg.value > 0) {
        // This is some buyer/staker who wants 
        // another party to exec something.
        // msg.data is the requested TX 
        // eg "this eth scription-> me pls"
        map[keccak256(msg.data)] = msg.value; // best data structure TBD

       // emit event? 
    } else {
       // this is a SC-DC escrow request 
       // requires someone has put up some stake for the tx
       require(map[keccak256(msg.data)]>0);
      uint256 amount = map[...]
       map[...] = 0 // reset to prevent reentrancy/replicated txs 
       (bool r,) = msg.sender.call{value: amount}('');
       require(r);
       // emit event?
    }
}
```

NOTE: Above code is demo and insufficient for the problem. Eg. Invalid txs are not validated/accounted for. Is that even doable in this DC land? 

Generic requests (think: collection bids) might be done by setting some fields in requested msg.data to 0...

**Comment by KenTheWhaleGoddess** [comment]
i think an oracle will eventually be needed to verify state

**Comment by dubuqingfeng** [comment]
What is the planned height of this proposal?

**Comment by RogerPodacter** [comment]
Block height 18684900!

But the docs are now at docs.facet.org
